### ISSUE TITLE
Multiple subscription inserts using API Explorer

### ISSUE THREAD

**Issue by BrennonEH** [AmbitEnergyLabs/Spoke#3]
Using the API Explorer to hit AddSubscription potentially creates duplicate subscriptions.

**Comment by mrudduck** [comment]
That behavior would be an issue with Nano's API Explorer and not related to Spoke. Spoke can be used with or without Nano, however I did use Nano in the demo project.

On the spoke side, we could consider adding dupe prevention into the add subscription method.

**Comment by randyburden** [comment]
@BrennonEH The specific duplicate submission bug has been fixed for Nano in the master branch but we haven't released an official version yet either the correction. Master is currently stable so feel free to pull in the latest or you'll have to wait for the release. Here is the original issue and fix: https://github.com/AmbitEnergyLabs/Nano/issues/72
