### ISSUE TITLE
Bad transform values

### ISSUE THREAD

**Issue by BrennonEH** [AmbitEnergyLabs/Spoke#4]
Bad transform JS of certain types can create blocking conditions that prevent additional events from being processed. Instead, the same few events will be processed over and over again.

**Comment by mrudduck** [comment]
Can you give an example where you saw this happen?

**Comment by BrennonEH** [comment]
I had nine subscriptions setup with bad transform values similar to the
below:

"requestObj.BrokerEventID = 300;
requestObj.BrokerReportedDate = '3-9-2016
requestObj.CustomerNbr = 300;
requestObj.EventDataString = 'test';"

I also had two subscriptions setup subsequently with no transform values
and that were otherwise correct.

The good subscriptions never activated until the bad transforms were
removed.

I have subscriptionactivity records with the error messages and timestamps
that might be useful.

**Comment by mrudduck** [comment]
I will take a look into the problem and let you know if i need more data.

Also, if you have a fix for the issue feel free to submit a pull request.

**Comment by rquach** [comment]
Ok, I found the problem. In the foreach where the subscriptions are evaluated, it rethrows the exception which will bubble it up and exit the foreach every time. I removed the throw in my PR.

**Comment by rquach** [comment]
PR #7 created to resolve issue.

**Comment by mrudduck** [comment]
Fix Merged. Let me know if you still see any issues
