### ISSUE TITLE
Expiration dates for events

### ISSUE THREAD

**Issue by BrennonEH** [AmbitEnergyLabs/Spoke#5]
Events may need an expiration date; If you get a backlog due to some error or congestion, due to parallelism you may end up with early bad data overwriting later good data as the stack races to resolve. Example: A customer changes their address, notices a typo, changes it again. If there is a backup in the stack, and then it unravels, it’s possible the first change arrives after the correction, and the typo becomes the ‘last in’ data.

**Comment by mrudduck** [comment]
You are correct, order is not guaranteed with this implementation ( or most webhooks implementations ). If you are worried about order you can add a date or identifier to your event so that you can determine the correct order.

**Comment by BrennonEH** [comment]
That would require any system using the event broker for data updates to
implement its own sub system for managing messaging continuity, essentially
creating another event broker behind the first.

Maybe I'm off base, but it seems like capturing data updates is going to be
a common use case for this tool. Wouldn't it make more sense to handle it
here?

**Comment by mrudduck** [comment]
There are numerous use cases, however the async nature of the broker would make an order guarantee very difficult.

Handling this on the consumer should be as simple as having an effective date or a history to see the date related to events you have already processed to determine whether or not to process the event you received.

If you have an idea on how you would implement some sort of order guarantee i would be happy to discuss it with you.

**Comment by BrennonEH** [comment]
I've got some ideas I'm kicking around, but I'm not familiar enough with
the design goals to say if they are appropriate. You want to meet up and
hash it out?
